####################################################
# EJS CONFIG （yaml形式）
####################################################

# サーバーのルートパス
config         :
  rootPath     : ''

####################################################
# head
####################################################

### サイト基本情報
site           :
  title        : 'Portfolio-braveworks'
  domain       : 'braveworks.github.io/portfolio'
  copyright    : '2016 braveworks.'

### メタ情報
meta           :
  description  : 'サイトの説明'
  # keyword      : 'キーワード'

### OGP
ogp            :
  default      :
    title      : ''
    type       : ''
    locale     : ''
    site_name  : ''
    description: ''
    url        : ''
    image      : ''

####################################################
# contents
####################################################

### cover skill set text
skillset:
  - Photoshop
  - Illustrator
  - Bootstrap
  - Responsive
  - JavaScript
  - jQuery
  - Gulp
  - Sass
  - EJS
  - PHP
  - WordPress
  - Git

dammy: 'http://placehold.it/200x200'

### content
products:
  -
    title       : 'プレミアムアプリ ランディングページ'
    url         : 'http://premium-appli.com/'
    image       : 'http://placehold.it/1900x3000'
    thumbnail   : 'http://placehold.it/400x400'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - 'スマートフォンアプリ制作サービスプロモーション用ランディングページ'
      - 'デザイン・HTML・CSS・JSコーディングの制作全般を担当。ScrollMagicを使用したパララックスアニメーションなどを実装しています'

  -
    title       : 'テスト2'
    url         : ''
    image       : 'http://placehold.it/400x400'
    thumbnail   : 'http://placehold.it/400x400'
    skill       :
      - 'Illustrator'
    description :
      - 'テスト説明'
      - 'テスト説明'
      - 'テスト説明'
