####################################################
# EJS CONFIG （yaml形式）
####################################################

# サーバーのルートパス
config          :
  rootPath      : ''

####################################################
# head
####################################################

### サイト基本情報
site            :
  title         : 'Portfolio-braveworks'
  domain        : 'braveworks.github.io/portfolio'
  copyright     : '2016 braveworks.'

### メタ情報
meta            :
  description   : 'サイトの説明'
  # keyword     : 'キーワード'

### OGP
ogp             :
  default       :
    title       : ''
    type        : ''
    locale      : ''
    site_name   : ''
    description : ''
    url         : ''
    image       : ''

####################################################
# contents
####################################################

### cover skill set text
skillset        :
  - Photoshop
  - Illustrator
  - Bootstrap
  - Responsive
  - JavaScript
  - jQuery
  - Gulp
  - Sass
  - EJS
  - PHP
  - WordPress
  - Git

dammy           : 'http://placehold.it/200x200'

### content
products        :

  # -----------------------------------
  -
    title       : 'プレミアムアプリ'
    type        : 'ランディングページ'
    label       : 'Landing Page'
    url         : 'http://premium-appli.com/'
    image       : 'images/ss-premium-appli-com.jpg'
    thumbnail   : 'images/ss-premium-appli-com.jpg'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - 'スマートフォンアプリ制作サービス プロモーション用ランディングページ'
      - 'デザイン・コーディング他・制作全般担当'
    publish     :
      - '株式会社オーエス (2015)'

  # -----------------------------------
  -
    title       : 'プレミアムリスティング'
    type        : 'サービスサイト'
    label       : 'Service Site'
    url         : 'http://premium-listing.com/'
    image       : 'images/ss-premium-listing-jp.jpg'
    thumbnail   : 'images/ss-premium-listing-jp.jpg'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - 'インターネット広告サービスプロモーション用サービスサイト'
      - 'デザイン・コーディング他・制作全般担当'
    publish     :
      - '株式会社オーエス (2015)'

  # -----------------------------------
  -
    title       : 'ホームページプレミアム v2'
    type        : 'サービスサイト'
    label       : 'Service Site'
    url         : 'http://homepage-premium.com/v2/'
    image       : 'http://placehold.it/1900x3000'
    thumbnail   : 'http://placehold.it/400x400'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - '中小企業向けホームページ制作代行サービスプロモーション用サービスサイト(リニューアル版）'
      - '※会社都合により非公開'
      - 'デザイン・コーディング他、制作全般担当'
    publish     :
      - '株式会社オーエス (2016)'

  # -----------------------------------
  -
    title       : 'ホームページプレミアム v1'
    type        : 'サービスサイト'
    label       : 'Service Site'
    url         : 'http://homepage-premium.com/'
    image       : 'images/ss-homepage-premium-com-v1.jpg'
    thumbnail   : 'images/ss-homepage-premium-com-v1.jpg'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - '中小企業向けホームページ制作サービスプロモーション用サービスサイト'
      - 'デザイン・コーディング他、制作全般担当'
    publish     :
      - '株式会社オーエス (2014)'

  # -----------------------------------
  -
    title       : 'ホームページプレミアム LP'
    type        : 'ランディングページ'
    label       : 'Landing Page'
    url         : 'http://homepage-premium.com/lp/'
    image       : 'images/ss-homepage-premium-com-lp.jpg'
    thumbnail   : 'images/ss-homepage-premium-com-lp.jpg'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - '中小企業向けホームページ制作代行サービスプロモーションサイト'
      - 'デザイン・コーディング他、制作全般担当'
    publish     :
      - '株式会社オーエス (2013)'

  # -----------------------------------
  -
    title       : 'コスト削減.bizモバイル'
    type        : 'サービスサイト'
    label       : 'Service Site'
    url         : 'http://www.costsakugen.biz/mobile/'
    image       : 'images/ss-costsakugen-biz-mobile.jpg'
    thumbnail   : 'images/ss-costsakugen-biz-mobile.jpg'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - '法人向け携帯電話導入サービス用サービスサイト'
      - 'デザイン・コーディング他、制作全般担当'
    publish     :
      - '株式会社C-mind様 (2014)'

  # -----------------------------------
  -
    title       : '株式会社オーエス採用サイト2016〜2017'
    type        : '採用サイト'
    label       : 'Recruit Site'
    url         : 'http://oscorporation.com/2007/'
    image       : 'http://placehold.it/1900x3000'
    thumbnail   : 'http://placehold.it/1900x3000'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - '株式会社オーエス求人用サイト(公開終了)'
      - 'デザイン・フロントエンド他、制作の全般を担当'
    publish     :
      - '株式会社オーエス (2015-2016)'

  # -----------------------------------
  -
    title       : '株式会社オーエス自社サイト'
    type        : 'コーポレートサイト'
    label       : 'Corporate Site'
    url         : 'http://oscorporation.com/'
    image       : 'images/ss-oscorporation-com.jpg'
    thumbnail   : 'images/ss-oscorporation-com.jpg'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - '自社コーポレートサイトのリニューアル'
      - 'デザイン・コーディング他、制作全般担当'
    publish     :
      - '株式会社オーエス (2013)'

  # -----------------------------------
  -
    title       : '歯科パーク'
    type        : '歯科検索サービス'
    label       : 'Service Site'
    url         : 'http://www.shika-park.jp/'
    image       : 'images/ss-shika-park-jp.jpg'
    thumbnail   : 'images/ss-shika-park-jp.jpg'
    skill       :
      - 'Photoshop'
    description :
      - '歯科検索サイト'
      - '担当：ベースデザイン・キャラクターデザイン・フロントエンド部分のコーディング・アニメーション制作'
    publish     :
      - '株式会社オーエス (2013)'

  # -----------------------------------
  -
    title       : 'ラムセスグループサイト'
    type        : 'コーポレートサイト'
    label       : 'Corporate Site'
    url         : 'http://ramses-grp.com/'
    image       : 'http://placehold.it/1900x3000'
    thumbnail   : 'http://placehold.it/400x400'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - 'コーポレートサイトリニューアル'
      - 'デザイン・コーディング他、制作全般担当'
    publish     :
      - 'サンポウ企業株式会社 (2016)'

  # -----------------------------------
  -
    title       : 'KJエンターテイメントサイト'
    type        : 'コーポレートサイト'
    label       : 'Corporate Site'
    url         : 'http://kjenta.com/'
    image       : 'images/ss-kjenta-com.jpg'
    thumbnail   : 'images/ss-kjenta-com.jpg'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - 'コーポレートサイト'
      - 'ベースデザイン・WordPressテーマ開発・アニメーション制作・他制作全般担当'
    publish     :
      - 'KJエンターテイメントサイト (2016)'

  # -----------------------------------
  -
    title       : '株式会社チャリングチャリンクスサイト'
    type        : 'コーポレートサイト'
    label       : 'Corporate Site'
    url         : 'http://charingchalinks.co.jp/'
    image       : 'images/ss-charingchalinks-co-jp.jpg'
    thumbnail   : 'images/ss-charingchalinks-co-jp.jpg'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - 'コーポレートサイト'
      - 'ベースデザイン・WordPress構築・テーマ開発・パララックス効果などのアニメーション、その他フロントエンド部分などを担当'
      - '※お客様都合により一部ページは未制作・非公開'
    publish     :
      - '株式会社チャリングチャリンクス (2016)'

  # -----------------------------------
  -
    title       : 'エルミタージュ'
    type        : 'サービスサイト'
    label       : 'Service Site'
    url         : 'http://aromaesthe.jp/'
    image       : 'images/ss-aromaesthe-jp.jpg'
    thumbnail   : 'images/ss-aromaesthe-jp.jpg'
    skill       :
      - 'Photoshop'
      - 'Gulp'
    description :
      - 'コーポレートサイト'
      - 'WordPress構築・テーマ開発・プラグインカスタマイズ・一部アニメーションなどのフロントエンド部分を担当（デザイン・ベースのマークアップ部分は別担当）'
    publish     :
      - 'KJエンターテイメントサイト (2016)'

  # -----------------------------------
  -
    title       : '手打そば車家'
    type        : 'サービスサイト'
    label       : 'Service Site'
    url         : ''
    image       : 'images/ss-soba-kurumaya-co-jp.jpg'
    thumbnail   : 'images/ss-soba-kurumaya-co-jp.jpg'
    skill       :
      - 'Photoshop'
    description :
      - 'プロトタイプデザイン（PSD）の作成を担当'
      - ''
    publish     :
      - '手打そば車家 (2016)'
  # -----------------------------------
  -
    title       : '炭火焼肉「龍炎」サイト'
    type        : 'サービスサイト'
    label       : 'Service Site'
    url         : 'http://www.ryuen2004.com/'
    image       : 'images/ss-.ryuen2004-com.jpg'
    thumbnail   : 'images/ss-.ryuen2004-com.jpg'
    skill       :
      - 'Photoshop'
    description :
      - 'プロトタイプ・トップページデザイン（PSD）を担当'
      - '※下層ページ等は別'
    publish     :
      - '龍炎 (2013)'
