####################################################
# EJS CONFIG （yaml形式）
####################################################

# サーバーのルートパス
config         :
  rootPath     : '/'

####################################################
#
####################################################

### サイト基本情報
site           :
  title        : 'Gulpテンプレート'
  domain       : 'homepage-premium.com'
  copyright    : '2016 OS Co.,Ltd.'

### メタ情報
meta           :
  description  : 'サイトの説明'
  # keyword      : 'キーワード'

### OGP
ogp            :
  default      :
    title      : ''
    type       : ''
    locale     : ''
    site_name  : ''
    description: ''
    url        : ''
    image      : ''

### Twitter Card
# twitter        :
#   default      :
#     site       : ''
#     card       : ''
#     description: ''
#     image      : ''
